### ISSUE TITLE
Switching layout with empty study crashes program

### ISSUE THREAD

**Issue by corbanmailloux** [7imbrook/262-imaging-studies-system#13]
1. Click File > New Study...
2. Save study as empty.stud
3. Click File > Open Study...
4. Open empty.stud 
5. Click View > Toggle Image View
Expected: Nothing
Actual: Program crashes

**Comment by corbanmailloux** [comment]
Project is long over.

**Comment by 7imbrook** [comment]
thanks @corbanmailloux

**Comment by Omodi** [comment]
For all the emails
